### ISSUE TITLE
Metal shader fails to compile on macOS Sonoma 14.8.x — "lambda expressions are not supported in Metal"

### ISSUE THREAD

**Issue by kutlay** [mike-ward/go-gui#126]
Running any go-gui app (including the stock `examples/get_started`) crashes immediately on startup with a Metal shader compilation error.

**Environment:**
- macOS: Sonoma 14.8.3 (build 23J220)
- go-gui: reproduced on both v0.41.1 and v0.42.0
- Go: 1.26.0 (darwin/arm64)
- Xcode Command Line Tools: reproduced on both 15.3 and 16.2 (updating CLT did not change the outcome)

**Steps to reproduce:**
```
go run github.com/go-gui-org/go-gui/examples/get_started@latest
```

**Error:**
```
2026-07-24 21:31:37.302 gs[21307:11383028] metal: compile shaders: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:249:19: error: lambda expressions are not supported in Metal
    auto unpack = [](float val1, float val2,
                  ^
" UserInfo={NSLocalizedDescription=program_source:249:19: error: lambda expressions are not supported in Metal
    auto unpack = [](float val1, float val2,
                  ^
}
panic: metal: metal: metal: metalCtxCreate failed

goroutine 1 [running, locked to thread]:
github.com/go-gui-org/go-gui/gui/backend/metal.Run(...)
	gui/backend/metal/backend.go:158
github.com/go-gui-org/go-gui/gui/backend.Run(...)
	gui/backend/run_darwin.go:12
main.main()
```

**Analysis:**
The MSL shader source compiled in `gui/backend/metal/metal_darwin.m` (around the gradient/fill shader, `newLibraryWithSource:` call near line 769/909) contains a lambda expression:
```
auto unpack = [](float val1, float val2, ...
```
This is compiled unconditionally as part of the single shared shader library at context-init time (`metalCtxCreate`), so it blocks *every* app on this OS regardless of whether the app actually uses gradients. The library compiles with `options:nil`, so no explicit `MTLLanguageVersion`/`languageVersion` is set — the default negotiated by this OS's Metal compiler apparently doesn't support lambda expressions in shader functions.

I confirmed this is not specific to my application code, my Go/CLT toolchain, or the go-gui version — it reproduces identically with the project's own minimal example on a clean module.

**Suggested fix:**
- Avoid lambda expressions in the MSL shader source (inline the `unpack` logic as a plain function or macro), and/or
- Explicitly set `MTLCompileOptions.languageVersion` to a version confirmed to support whatever feature is needed, with a graceful fallback/error path instead of a hard panic when shader compilation fails.

**Comment by kutlay** [comment]
A note: updating to the latest MacOS version Tahoe 26.5.2 and using llvm 19.1.5 by setting the CC environment variable solved the problem for me.

```
export CC=/opt/homebrew/Cellar/llvm/19.1.5/bin/clang
go run github.com/go-gui-org/go-gui/examples/get_started@latest
ld: warning: ignoring duplicate libraries: '-lobjc'
```

I get a warning but it seems to work

**Comment by mike-ward** [comment]
Thanks for the bug report. The warning is expected. Something about how the linker works makes it unavoidable. Don't understand the issue, but AI says it's normal. Bummer because I do not like having warnings in my builds.

**Comment by mike-ward** [comment]
Fixed on `main` in #127 (commit 7f687e6). Not yet in a tagged release — next release after v0.42.0 will carry it.

**Root cause.** Your analysis was correct. Lambda expressions require Metal 3.2 (macOS 15 Sequoia). The gradient shader's `auto unpack = [](...)` was fine on the machine that built it and invalid everywhere older. Because the MSL library is compiled once in `metalCtxCreate`, the failure took down *every* app on Sonoma, gradients or not.

The reason it shipped at all: `newLibraryWithSource:options:nil` lets the accepted feature set silently follow whatever OS the compile runs on. No pin, no build-time error, no CI coverage.

**What changed.**

- **Lambda removed.** Replaced with a plain static function. It captured nothing, so the lift is semantics-preserving — body and call-site arguments unchanged.
- **`MTLCompileOptions.languageVersion` pinned** on the built-in library: macOS to 3.0 (Ventura floor), iOS to 2.4 (matching the iOS 15 deployment target — 3.0 is iOS 16+, so pinning higher would have reproduced the same bug on iOS). User-supplied shaders in `metalBuildCustomPipeline` keep `options:nil`; their OS floor is the caller's decision.
- **Shader source de-duplicated into Go** (`gui/backend/internal/msl`). The macOS and iOS backends carried byte-identical 428-line copies of the MSL, which is why a shader fix had to be applied twice. A shared `.h` was the first attempt but it lives outside both package dirs and is invisible to the Go build cache — editing the shader would silently reuse a stale binary. A Go constant is tracked correctly.
- **Regression test added.** `TestBuiltinShadersCompile` compiles the library standalone at the pinned version via a probe entry point. Worth noting: the real compile needs a window and is gated behind `GO_GUI_MAIN_THREAD_TESTS`, which no CI job sets — so nothing on any runner was compiling a shader before this. Verified the new test fails when a lambda is reintroduced.

Not adopting the graceful-fallback half of the suggestion for now. A shader that fails to compile leaves nothing renderable, so the panic is honest; the fix is to not ship invalid MSL, which the pin plus the test now enforce at build time.

@kutlay — the `CC=` / llvm workaround shouldn't be needed once this is released; it was the newer macOS, not the compiler, that got you past it. If you can re-test against `main` on Sonoma before the next tag, that'd be a useful confirmation.
